name: develop-workflow
concurrency: #avoid concurrent runs on label events, might cause issues on super fast commits  ¯\_(ツ)_/¯
  #group: ${{ join(github.event.pull_request.labels.*.name, ',') }}
  group: ${{ github.head_ref }}
  #cancel-in-progress: true

on:
  push:
    paths-ignore:
      - '.github/**'
    branches: [ develop ]

jobs:

  new-build-started:
    runs-on: ubuntu-latest
    name: 'Build and Push Docker Image'
    permissions:
      id-token: write	
      contents: read
      actions: read	
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: 'arn:aws:iam::${{ secrets.AWS_DEV_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_TO_PUSH_IMG }}'
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        if: steps.aws_account.outputs.accountId
        uses: aws-actions/amazon-ecr-login@v1
      
